Repository team-memories/memories, pull requests merged in 2020-11, with the labels that each got.

#23 fix: Fix graphql schema error
  src/web/src/App.js
  src/web/src/components/Media/MediaComment/media-add-comment.js
  src/web/src/components/Media/media-detail-card-query.js
  src/web/src/components/Media/media-list.js
  src/web/src/components/Media/media-search-query.js
  src/web/src/components/UploadPage/upload-tags-select.js
  src/web/src/pages/media-modify-page.js
  src/web/src/pages/media-view-page.js
  src/web/src/pages/upload-page.js
  src/web/src/pages/user-page.js
Labels: Front-end, bug

#24 Refactor(server) data status #20
  src/server/data-sources.js
  src/server/migrations/20201103232156_comment_active_flag.js.js
  src/server/resolvers/comment.js
  src/server/resolvers/media.js
  src/server/resolvers/mutation.js
  src/server/resolvers/query.js
  src/server/schema.js
  src/web/package-lock.json
  src/web/src/components/Media/MediaComment/media-comment.js
  src/web/src/components/Media/media-search-query.js
  src/web/src/pages/login-page.js
  src/web/src/pages/register-page.js
Labels: Back-end, Front-end, refactoring

#25 feat(server): add createdAt field and sorting
  src/server/data-sources.js
  src/server/migrations/20201117133130_created_at_field.js
Labels: Back-end, enhancement, refactoring

#26 Change url
  src/server/data-sources.js
  src/server/migrations/20201118215238_change_url.js
  src/server/resolvers/mutation.js
  src/web/package-lock.json
Labels: Back-end, refactoring

#27 Add tags
  src/server/data-sources.js
  src/server/resolvers/query.js
  src/server/schema.js
  src/web/src/components/UploadPage/upload-tags-select.js
  src/web/src/components/constants.js
  src/web/src/pages/media-modify-page.js
  src/web/src/pages/upload-page.js
Labels: Back-end, Front-end, enhancement, refactoring

#28 Refactor front
  .gitignore
  src/server/data-sources.js
  src/server/migrations/20201124214834_create_google_id.js
  src/server/resolvers/mutation.js
  src/server/schema.js
  src/web/package-lock.json
  src/web/package.json
  src/web/src/components/SignPage/google-login-button.js
  src/web/src/components/SignPage/google-register-button.js
  src/web/src/components/UserPage/user-deactivate-button.js
  src/web/src/pages/login-page.js
  src/web/src/pages/register-page.js
  src/web/src/pages/user-page.js
  src/web/src/style/style.css
Labels: Front-end, enhancement, refactoring

#31 fix(front): Fix user deactivate error
  src/web/src/components/UserPage/user-deactivate-button.js
  src/web/src/pages/user-page.js
Labels: Front-end, bug

#32 Frontend refactoring
  src/web/src/components/Header/header-icons-userMenu.js
  src/web/src/components/SignPage/google-login-button.js
  src/web/src/components/SignPage/google-register-button.js
  src/web/src/components/SignPage/login-page-button.js
  src/web/src/components/SignPage/register-page-button.js
  src/web/src/components/SignPage/register-page-name.js
  src/web/src/components/SignPage/sign-page-email.js
  src/web/src/components/SignPage/sign-page-password-confirm.js
  src/web/src/components/SignPage/sign-page-password.js
  src/web/src/components/UserPage/user-deactivate-button.js
  src/web/src/pages/login-page.js
  src/web/src/pages/register-page.js
  src/web/src/pages/user-page.js
  src/web/src/style/style.css
Labels: Front-end, enhancement, refactoring

#34 refactor(server/frontend): add edit user info page
  src/server/data-sources.js
  src/server/resolvers/mutation.js
  src/server/schema.js
  src/web/src/App.js
  src/web/src/components/SignPage/sign-page-password-confirm.js
  src/web/src/components/SignPage/sign-page-password.js
  src/web/src/components/UploadPage/upload-tags-select.js
  src/web/src/components/UserPage/user-deactivate-button.js
  src/web/src/components/UserPage/user-edit-button.js
  src/web/src/pages/user-edit-page.js
  src/web/src/pages/user-page.js
Labels: Back-end, Front-end, enhancement, invalid, refactoring
